### ISSUE TITLE
Question: Is there a way to switch to ksdiff if you don't extend SnapshotTestCase?

### ISSUE THREAD

**Issue by timbroder** [pointfreeco/swift-snapshot-testing#166]
We extend `QuickSpec` and I'm hoping to also have error formatting be handled for ksdiff

thanks!

**Comment by mbrandonw** [comment]
@timbroder Are you running tests on macOS or Linux?

Subclassing `SnapshotTestCase` is only necessary (and even possible) on Linux, due to the fact that it doesn't (yet) support `XCTWaiter`.

If you are on macOS, then you must be using the free function `assertSnapshot` without subclassing. And in that case the `diffTool` configuration is just a global variable that you can set from anywhere:

https://github.com/pointfreeco/swift-snapshot-testing/blob/345b06a77bcc9eef40312fbade70222277d62a98/Sources/SnapshotTesting/AssertSnapshot.swift#L4-L7

**Comment by timbroder** [comment]
Thanks!

Should this work?

![image](https://user-images.githubusercontent.com/121503/51770641-732c5c80-20b4-11e9-8c75-5059171c6bc5.png)

**Comment by mbrandonw** [comment]
That's not quite right. That is create an all new `diffTool` variable, rather than overwriting the one that exists in there `SnapshotTesting` module.

Can you try creating a `beforeEach` in your spec that sets `diffTool = "ksdiff"` and see if that works? If you use a base test case that everything inherits from you could also set it in there.

**Comment by timbroder** [comment]
That did it, thanks!
