### ISSUE TITLE
Async Initializer cause internal error occured on XCode

### ISSUE THREAD

**Issue by ali991** [pointfreeco/swift-snapshot-testing#171]
Hi there,

Using Async initializer described on Readme, i'm getting this error on my XCode editor (10.1)

just paste this code and you'll get the error:

extension Snapshotting where Value == UIViewController, Format == UIImage {
    public static let image = Snapshotting(
        pathExtension: "png",
        diffing: .image,
        asyncSnapshot: { viewController in
            Async { callback in
                //Code to take a snapshot
            }
    } 
    )
}

![screen shot 2019-02-11 at 11 54 46 am](https://user-images.githubusercontent.com/10392374/52581631-34f3a480-2df9-11e9-8223-4b469db274d4.png)

**Comment by mbrandonw** [comment]
Hi @ali991 thanks for reporting this! Turns out we never extracted the image diffing strategy to a static `Diffing<UIImage>.image`, and so that why it isn't compiling (really the compiler is segfaulting which is why you aren't getting a good error message).

This PR https://github.com/pointfreeco/swift-snapshot-testing/pull/172 fixes that and then the snippet should work.

**Comment by mbrandonw** [comment]
@ali991 the PR has been merged, and so if you use master you shouldn't have this problem. Can you confirm?

Thanks!

**Comment by ali991** [comment]
thanks for your commit @mbrandonw ,

but I just pulled from master, and the problem still persist.

**Comment by mbrandonw** [comment]
Strange, it's working for me. Are you definitely building for iOS and not macOS?

**Comment by ali991** [comment]
it is now working thanks!, just build problem.

**Comment by mbrandonw** [comment]
Good to hear! Will close this issue.
