### ISSUE TITLE
Add Issue/Pull Request Templates

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#175]
It'd be nice to capture frequently asked questions, like the fact that the same simulator must be used on CI.

**Comment by marcosgriselli** [comment]
I like the issue template on https://github.com/stevemao/github-issue-templates/blob/master/no-duplicates/ISSUE_TEMPLATE.md with some adjustments. Adding a few fields encourages the author to think about his issue from a different angle and even find alternatives he didn't consider before. 

⬇️

Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [ ] I've read the FAQ before creating this issue

## Expected Behavior



## Current Behavior



## Possible Solution



## Steps to Reproduce (for bugs)


1.
2.
3.
4.

## Context




## Environment

* SnapshotTesting version:
* Device and OS running tests:
* Xcode version:
* Demo project link:

[ISSUE_TEMPLATE.md.zip](https://github.com/pointfreeco/swift-snapshot-testing/files/2867260/ISSUE_TEMPLATE.md.zip)

**Comment by marcosgriselli** [comment]
Creating a FAQ document can probably be an iterative process. Push a FAQ section with 1 or 2 Q&As and keep adding them as users repeat the same questions. Plus it will let contributors send small PRs adding new Q&As so no one gets the task of writing it entirely on their own.

**Comment by stephencelis** [comment]
Thanks for the suggestions! This isn't a super high-priority thing right now so I'm going to close, but with our recent open-sourcing of swift-composable-architecture it's something we'd like to solve for there, too. So we'll hopefully address in the near future!
