### ISSUE TITLE
Change XcodeGen dependency as private

### ISSUE THREAD

**Issue by inamiy** [pointfreeco/swift-snapshot-testing#201]
Hi @pointfreeco team 👋 

I just noticed that 1fb2e65c (adding XcodeGen dependency) leads end-users to also pull all of its unused dependency, and it is quite painful to me.

I don't think Swift Package Manager provides a clever way of separating it as a private dependency (e.g. like Carthage using `Cartfile.private`), but I would like to have at least environment variable switching to work around.  

e.g. Example code can be found in Quick.
https://github.com/Quick/Quick/blob/a0e1457029c2a451a321fdd3a6a6f36ac367010f/Package.swift

**Comment by stephencelis** [comment]
@inamiy That's really clever! We hadn't considered scoping development dependencies in that fashion, but it makes perfect sense. We've been using XcodeGen all over in order to support Carthage, and locking to a specific XcodeGen version with `Package.swift` was very helpful, but we'd love to scope its use to an environment variable. Will look into this soon!

**Comment by inamiy** [comment]
@stephencelis Good to hear! I will wait for your update 😄

**Comment by stephencelis** [comment]
@inamiy Did a quick test and it works great: https://github.com/pointfreeco/swift-tagged/pull/19/commits/77bdcc17f31040bc1b415a1bbd457e400b8aa385

We'll update all our repos soon accordingly!

**Comment by stephencelis** [comment]
This is done!
