### ISSUE TITLE
Cannot snapshot UIWindow instance with device

### ISSUE THREAD

**Issue by whoyawn** [pointfreeco/swift-snapshot-testing#257]
```
let window = UIWindow()
assertSnapshot(matching: window, as: .image(on: .iPhoneX)) // Generic parameter 'Format' could not be inferred
```

This works, however, when I don't have the device configuration call:

```
assertSnapshot(matching: window, as: .image)
```

**Comment by gabrieloc** [comment]
Running into the same issue. Recent regression?

**Comment by stephencelis** [comment]
Hi @whoyawn! Sorry for the delay. This is because `on:` is only available on `UIViewController`, _not_ `UIView`: https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Available-Snapshot-Strategies.md#image-11 You can add your view to a view controller to get access to device-specific view configurations.
