### ISSUE TITLE
Missing trait configurations

### ISSUE THREAD

**Issue by chosa91** [pointfreeco/swift-snapshot-testing#258]
I want to ask that, why in the `Sources/SnapshotTesting/Common/View.swift` file the `UITraitCollection` extension methods has `displayGamut` and `displayScale` commented out?
Also, it is welcomed with a PR to add missing devices?

**Comment by stephencelis** [comment]
Those are commented out because, in our experience, they don't actually behave correctly. Particularly, a P3 simulator will always render its images with P3 gamut, and an sRGB simulator will always render its images with sRGB. Scale is also not consistent across 2x devices and 3x devices. We should maybe add a `NB:` (nota bene) comment explaining this.

And yep, missing devices are totally welcome as a PR!

**Comment by stephencelis** [comment]
Going to close this out to help focus GitHub issues on bugs. Will welcome PRs and documentation improvements, though, thanks!
