### ISSUE TITLE
Snapshot-testing and github actions

### ISSUE THREAD

**Issue by MatteoBatti** [pointfreeco/swift-snapshot-testing#291]
Hi
I have setup  some snapshot tests for our projects and to run the tests I'm using fastlane in order to force the device where the screenshots were originally taken.
Everything seems good, tests run with success across team macs, but we are getting a failure when we run them using github actions for CI.

we are using both `.image` and `.recursiveDescription` strategies and for both the failure reason is `failed - Snapshot does not match reference.`

is there a way get a more explicative log?

**Comment by ixrevo** [comment]
Hi @MatteoBatti 
I encountered a similar issue with our CI, and it could be caused by unmatched iOS SDK versions and/or Simulator models. For example, record a snapshot on iPhone 8, run on iPhone 11, and you will get a failure (coordinates of views differ by some fractions). The same with iOS 12 and iOS 13, even on the same simulator model.
Also, if you CI setup doesn't have the requested in Fastfile simulator model it will fallback to some default one. Check your CI logs to be sure you are using the same Simulator/SDK locally and on CI.

> is there a way get a more explicative log?
With Xcode 11 you can save `xcresult` file containing your tests results with all screenshots and attachments. It's located in `DerivedData/<Project Dir>/Logs/Test/xxx.xcresult` This file can be opened with Xcode and looks pretty much the same as your local test run. But it requires some additional setup in your CI build scripts.

**Comment by MatteoBatti** [comment]
Hi @ixrevo 
thanks for the quick response, the issue was related to the different timezone in the CI environment, the screenshots were actually different.

here the lane we used to move the xcresults:
```
      lane :test do |options|
            tests_passed = scan(scheme: "URBITicket", fail_build: false)

            if not tests_passed
                derived_data_path = lane_context[SharedValues::SCAN_DERIVED_DATA_PATH]
                archive_xcresults(derived_data_path: derived_data_path)
                UI.user_error!("Tests failed")
            end
        end

        lane :archive_xcresults do |options|
            test_logs_folder_path = "#{options[:derived_data_path]}/Logs/Test"

            if File.exist?(test_logs_folder_path)
                project_dir = File.expand_path("..", Dir.pwd)
                test_results_folder = "#{project_dir}/testresults"
                Dir.mkdir(test_results_folder)
                xcresults = Dir["#{test_logs_folder_path}/*.xcresult"]
                xcresults.each do |xcresult|
                    puts "copying #{xcresult} to #{test_results_folder}"
                    FileUtils.cp_r(xcresult, test_results_folder)
                end

            else
                puts "No test logs folder"
            end
        end
```
and here the github action to upload the xcresults:

```
    - name: Archive xcresults
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: testresults
        path: testresults
```
