### ISSUE TITLE
 iOS 13.3 : Snapshots fail if recorded while the simulator is in portrait and tested while the simulator is in landscape.

### ISSUE THREAD

**Issue by quennevillels** [pointfreeco/swift-snapshot-testing#314]
```
var iPadPortrait: Snapshotting<UIViewController, UIImage> { return .image(on: .iPadMini(.portrait)) }

func validateStandardSnapshots(matching value: UIViewController,
                                   name: String = "",
                                   file: StaticString = #file,
                                   testName: String = #function,
                                   line: UInt = #line) {

    assertSnapshot(matching: value, as: iPadPortrait, named: name + "ipad_portrait", file: file, testName: testName, line: line)
}
```
Hi guys,

The above code works with iPad Air 2 (iOS 12.4) simulator no matter the orientation of the simulator when testing. However, this code fails when running on an iPad Air 2 (iOS 13.3) simulator where the recording was done in portrait but the testing was done in landscape.

SnapshotTesting version 1.7.1

Using:
Xcode 11.3.1 
Mojave 10.14.6

**Comment by stephencelis** [comment]
Hi @quennevillels, thanks for reporting! We recommend running tests with a consistent configuration because there is only so much we can work around in the unknowable world of Apple's APIs and how they affect view rendering over the course of iOS versions. You might want to file feedback about this change with Apple if you believe it is regression or bug.

We'd definitely take a workaround if you find one, but in the meantime we'd recommend documenting how tests should be run with the team and ensure that they're run in a consistent manner. You might even be able to write some tooling around setting a simulator's orientation automatically before running the tests.

I'm doing some issues housekeeping in order to try to focus them in on bugs in the library. While it'd be nice to have a workaround for this, I think it would be considered an "enhancement" rather than a "bug fix" since it is preventable by running tests in a controlled way. Cool if I close and tag it as such?

**Comment by quennevillels** [comment]
Thanks @stephencelis for getting back to me. 

I've got no issue with making this an enhancement. 

All the best to you and your team.

**Comment by stephencelis** [comment]
Thanks! Hopefully Apple makes this kind of thing easier to handle in the future.
