### ISSUE TITLE
Things to snapshot

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-snapshot-testing#52]
- [ ] NSAttributedString
- [x] SCNView
- [ ] URL
- [x] URLRequest
- [x] UIView recursive description
- [ ] signal
- [x] json 
- [x] plist
- [x] html

**Comment by mackoj** [comment]
Should we consider snapshotting memory, cpu, network (volume of data transmitted) and disk usage ? @mbrandonw

**Comment by mackoj** [comment]
Do you think it's possible to snapshot generated interface of a swift file? 
The goal is to see if we can compare public interface of a file and see if it has changed ?

<img width="1678" alt="capture d ecran 2018-12-18 a 23 22 58" src="https://user-images.githubusercontent.com/661647/50984215-a346fd80-1501-11e9-945f-85949a67d3fb.png">

**Comment by Sherlouk** [comment]
For `URL` is there a reason you wouldn't simply compare `absoluteString` also maybe an option to compare URLComponents (nicer breakdown vs URL on it's own)?

**Comment by Sherlouk** [comment]
> Do you think it's possible to snapshot generated interface of a swift file?

In Swift 5 a `.swiftinterface` file is created ([link](https://forums.swift.org/t/plan-for-module-stability/14551)) which is a textual representation of the public/open interface for the library.

Should be fairly doable to use `__XCODE_BUILT_PRODUCTS_DIR_PATHS` to load that file - snapshot it locally with the test and run a comparison.

(Should say I'm not running Swift 5 at the mo otherwise I'd jump on prototyping this, sounds like an interesting idea)

**Comment by mackoj** [comment]
@Sherlouk @stephencelis Thanks for the replies.

For `.swiftinterface` it will be for Swift 5.1 for [module stability](https://swift.org/blog/5-1-release-process/).

For the memory and CPU snapshot we could use `task_info` API ?

**Comment by stephencelis** [comment]
I'm doing some spring cleaning and am closing issues that don't have an obvious fix, like this one 😄 Great discussion and ideas in this thread, though. When GitHub Discussions rolls out we should consider it as a forum for exploring new snapshot strategy ideas. Till then, if you come up with something you'd like to PR, we'd love to see it!
