### ISSUE TITLE
No new releases since Apr 2021 - 1.9.0 

### ISSUE THREAD

**Issue by alrocha** [pointfreeco/swift-snapshot-testing#574]
Hi folks! 

Why it has no been releases lately? for those who use semantic versions in packages, we can't have the latest fixes unless we point to master, is there any reason behind it? 

Thanks

**Comment by stephencelis** [comment]
Hi @alrocha!

The core of SnapshotTesting is pretty stable and no changes have been staged since 1.9.0. This means the interfaces used to create snapshot strategies and take snapshots are currently in the same state that they are in your project.

Snapshot strategies themselves need a bit more care when cutting releases, and so we need to be careful when doing so. The more volunteers we have to test the `main` branch, the more quickly we will be able to cut new releases without unintentionally breaking things for everyone.

One thing that would be helpful is some verification from the community that the changes staged on `main` are non-breaking. If you have projects utilizing SnapshotTesting, would you be interested in contributing some time to verify that they still behave as expected when building from `main`?

Our goal for SnapshotTesting 2.0.0 is to decouple the core library, which manages the core types and logic around serialization, deserialization, and XCTest integration, with the strategies, like the image strategies and UIKit/SwiftUI strategies, along with some kind of versioning system. This will hopefully remove some of the blockers that prevent releases from happening at a quicker pace right now.

**Comment by Jon889** [comment]
Sorry to jump in, just wondering how making new versions could unintentionally break things for consumers of the library as they can stay on the older version?

(for context I'm on an M1 while my CI is not, and I'm having to use the fork from this PR https://github.com/pointfreeco/swift-snapshot-testing/pull/571 so was wondering when it could be released, then realised the last release was in April, which made me reconsider using this library as usually that's an indicator a project isn't maintained anymore)

**Comment by stephencelis** [comment]
> Sorry to jump in, just wondering how making new versions could unintentionally break things for consumers of the library as they can stay on the older version?

The main thing we want to prevent are breaking changes between minor releases. Ideally a library consumer can use `from:` in SPM to safely accept new versions, and this is how most folks configure their Package.swift files.

> (for context I'm on an M1 while my CI is not, and I'm having to use the fork from this PR #571 so was wondering when it could be released, then realised the last release was in April, which made me reconsider using this library as usually that's an indicator a project isn't maintained anymore)

If you'd like to volunteer some of your time to help test your snapshot artifacts pass on both `1.9.0` and `main`, you could help us expedite the release 😄

**Comment by XabierGoros** [comment]
> The core of SnapshotTesting is pretty stable and no changes have been staged since 1.9.0. This means the interfaces used to create snapshot strategies and take snapshots are currently in the same state that they are in your project.
> 
> Snapshot strategies themselves need a bit more care when cutting releases, and so we need to be careful when doing so. The more volunteers we have to test the `main` branch, the more quickly we will be able to cut new releases without unintentionally breaking things for everyone.

I absolutely agree with you @stephencelis, changes have to be tested carefully. It is true though there are some quite interesting PR for the library (I'm another one suffering with the Apple Silicon issue). Perhaps finding a middle way choosing a few PR and creating pre releases tagged versions could work?

> Our goal for SnapshotTesting 2.0.0 is to decouple the core library, which manages the core types and logic around serialization, deserialization, and XCTest integration, with the strategies, like the image strategies and UIKit/SwiftUI strategies, along with some kind of versioning system. This will hopefully remove some of the blockers that prevent releases from happening at a quicker pace right now.

That sounds a pretty nice architecture change, which among other things will ease the release flow for sure.

**Comment by ugiacoman** [comment]
++ to the discussion here. 

Our team is also pointing to the fork in #571. If the concern is that there are more untested, pending changes blocking a release, may I suggest you cut a hotfix release that only includes the changes in #571? This will add the functionality that many engineering teams need and also give the community / maintainers enough time to test all the other pending changes.

**Comment by simondelphia** [comment]
+1 for fixing the M1 issue; we've had to reduce the fuzzy precision and the result is the snapshot tests are missing things.

* Would also like to see a fix for #453 / #564 as that's a pretty problematic bug

**Comment by choulepoka** [comment]
This topic is of great interest to me personally / professionally, as I am myself running all my projects off `main` branch because some bug fixes have not been released yet, even though they are a few months old.

**Comment by teameh** [comment]
> The core of SnapshotTesting is pretty stable and no changes have been staged since 1.9.0. This means the interfaces used to create snapshot strategies and take snapshots are currently in the same state that they are in your project.

If would be cool to get https://github.com/pointfreeco/swift-snapshot-testing/pull/443 released to fix webview snapshots!

**Comment by sprejjs** [comment]
Hi Team,

I would also like to volunteer to speed things up. This project has been very promising so far, let's not allow it to die, please.

How can I help?

Thanks!

**Comment by joliejuly** [comment]
Hi guys! 

I am suffering from the M1 issue, too. 

It's been a year since the latest release. Just a thought - may be you may consider making a minor release with https://github.com/pointfreeco/swift-snapshot-testing/pull/571 and some other fixes which most likely won't break anything for others but will help tremendously all who is on M1 now?

Thanks!

**Comment by teameh** [comment]
1.9.0 😱 was released! https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.9.0

**Comment by simondelphia** [comment]
That was a year ago...?

**Comment by teameh** [comment]
Haha never mind.. I blame it on the Monday morning... 😅

**Comment by simondelphia** [comment]
Got me excited

**Comment by teameh** [comment]
Haha yeah shit me too..

**Comment by simondelphia** [comment]
@stephencelis any details on how to volunteer to help speed things up?

**Comment by YogeshBhattGWL** [comment]
> joliejuly

I am too facing issue on Mac M1.
I cant run Test cases. 
I am getting error:

`Undefined symbols for architecture x86_64:`

**Comment by stephencelis** [comment]
Finally going to close this one out 😅

Be careful with your upgrades! You may need to regenerate and re-audit your snapshots!

https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.10.0

**Comment by teameh** [comment]
Awesome! Thanks for the hard work, much appreciated! 🥳
